name: sbom releaser project

on:
  # For manual tests.
  workflow_dispatch:
    inputs:
      release-tag:
        description: "Release tag to test"
        required: false
        default: v0.0.1
        type: string
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

permissions: read-all

jobs:
  # TODO: build using SLSA compliant builder
  build:
    outputs:
      file: ${{ steps.file.outputs.name }}
    if: ${{ startsWith(github.ref, 'refs/tags/') }} # another comment
    runs-on: ubuntu-latest
    permissions:
      contents: write # Just a comment
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Upload binary
        env:
          GITHUB_TOKEN: ${{ github.token }}
          TAG: ${{ github.ref }}
        run: |
          version=$(echo "$TAG" | cut -f3 -d '/')
          gh release upload "$version" ./example
      - name: Artifact name
        id: file
        run: echo "name=example" >> $GITHUB_OUTPUT
          
  
  # SLSA-3 compliant SBOM builder.
  sbom:
    needs: [build]
    # Always run, even when the build job is skipped.
    if: always()
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      packages: write
      actions: read # For the entrypoint.
    uses: laurentsimon/sbom-action/.github/workflows/slsa3.yml@feat/slsa-trw
    with:
      # NOTE: file is empty on workflow_dispatch, and the SBOM
      # will use repository source code instead of the binary.
      file: ${{ needs.build.outputs.file }}
      artifact-name: "example.spdx.sbom"

  # test output
  # debug:
  #   needs: [release]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - env:
  #         SOME_OUTPUT: ${{ needs.release.outputs.some-output }}
  #         OTHER_OUTPUT: ${{ needs.release.outputs.other-output }}
  #         ATTESTATION_NAME: ${{ needs.release.outputs.attestations-download-name }}
  #       run: |
  #         #TODO: test with json
  #         # TODO: verify
  #         echo "SOME_OUTPUT: $SOME_OUTPUT"
  #         echo "OTHER_OUTPUT: $OTHER_OUTPUT"

  #         echo "ATTESTATION_NAME: $ATTESTATION_NAME"
