name: delegate release project

on:
  # For manual tests.
  workflow_dispatch:
    inputs:
      release-tag:
        description: "Release tag to test"
        required: false
        default: v1
        type: string
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

permissions: read-all

jobs:
  # release.
  release:
    permissions:
      id-token: write # For signing.
      contents: write # For asset uploads.
      packages: write
      actions: read # For the entrypoint.
    uses: laurentsimon/slsa-delegated-tool/.github/workflows/tool1_slsa3.yml@main
    with:
      name1: value1
      name2: value2
      private-repository: true
    secrets:
      secret1: "secret1-ehiecincivvjenvrvbrv"
      secret2: "secret2-ouxefnwiauhfcurifnerfc"

  # test output
  debug:
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - env:
          SOME_OUTPUT: ${{ needs.release.outputs.some-output }}
          OTHER_OUTPUT: ${{ needs.release.outputs.other-output }}
        run: |
          #TODO: test with json
          # TODO: verify
          echo "SOME_OUTPUT: $SOME_OUTPUT"
          echo "OTHER_OUTPUT: $OTHER_OUTPUT"
